"""
Django settings for config1 project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv
from split_settings.tools import include

# Добавление чувствительных данных в файл.

load_dotenv()

# Добавление настроек разнесенных по файлам.

include(
    'components/database.py',
    'components/definition_app.py',
    'components/valid_pass.py',
    'components/internationalization.py',
    'components/static_files.py',
    'components/default_type_primkey.py',
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']
